In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv('CKD.csv')

In [4]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [9]:
indep

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [10]:
dep

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
from sklearn.model_selection import GridSearchCV
param_grid={'n_neighbors':[5,6,7],
             'weights':['uniform', 'distance'],
           'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],
           'metric':['minkowski','str']} 
grid=GridSearchCV(KNeighborsClassifier(),param_grid,verbose=3,refit=True,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
120 fits failed out of a total of 240.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'pyfunc', 'mahalanobis', 'jaccard', 'cosine', 'canberra', 'correlation', 'yule', 'russellrao', 'manhattan', 'sqeuclidean', 'euclidean', 'minkowski', 'l2', 'infinity', 'nan_euclidean', 'sokalsneath', 'sokalmichener', 'chebyshev', 'dice', 'rogerstanimoto', 'p', 'seuclidean', 'braycurtis', 'l1', 'precomputed', 'haversine', 'cityblock', 'hamming'} or a callable. Got 'str' instead.

--------------------------------------------------------------------------------
22 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'cityblock', 'sokalsneath', 'hamming', 'l2', 'correlation', 'yule', 'infinity', 'pyfunc', 'l1', 'chebyshev', 'mahalanobis', 'p', 'sokalmichener', 'haversine', 'sqeuclidean', 'canberra', 'braycurtis', 'manhattan', 'euclidean', 'precomputed', 'cosine', 'jaccard', 'dice', 'nan_euclidean', 'minkowski', 'seuclidean', 'rogerstanimoto', 'russellrao'} or a callable. Got 'str' instead.

--------------------------------------------------------------------------------
14 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'precomputed', 'rogerstanimoto', 'sqeuclidean', 'manhattan', 'infinity', 'jaccard', 'l1', 'braycurtis', 'hamming', 'euclidean', 'sokalsneath', 'minkowski', 'mahalanobis', 'dice', 'haversine', 'p', 'russellrao', 'cosine', 'l2', 'nan_euclidean', 'canberra', 'sokalmichener', 'seuclidean', 'correlation', 'chebyshev', 'yule', 'cityblock', 'pyfunc'} or a callable. Got 'str' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'infinity', 'l2', 'hamming', 'l1', 'euclidean', 'sokalmichener', 'cityblock', 'mahalanobis', 'pyfunc', 'jaccard', 'braycurtis', 'cosine', 'sokalsneath', 'manhattan', 'dice', 'rogerstanimoto', 'seuclidean', 'precomputed', 'haversine', 'nan_euclidean', 'canberra', 'p', 'yule', 'sqeuclidean', 'chebyshev', 'minkowski', 'correlation', 'russellrao'} or a callable. Got 'str' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'euclidean', 'infinity', 'correlation', 'chebyshev', 'minkowski', 'jaccard', 'pyfunc', 'cityblock', 'canberra', 'hamming', 'cosine', 'dice', 'haversine', 'seuclidean', 'sokalmichener', 'l1', 'precomputed', 'sokalsneath', 'p', 'yule', 'braycurtis', 'rogerstanimoto', 'l2', 'sqeuclidean', 'russellrao', 'mahalanobis', 'manhattan', 'nan_euclidean'} or a callable. Got 'str' instead.

--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'hamming', 'p', 'sokalmichener', 'infinity', 'pyfunc', 'cosine', 'dice', 'yule', 'minkowski', 'precomputed', 'l2', 'rogerstanimoto', 'haversine', 'euclidean', 'mahalanobis', 'correlation', 'sqeuclidean', 'nan_euclidean', 'braycurtis', 'manhattan', 'chebyshev', 'canberra', 'russellrao', 'jaccard', 'sokalsneath', 'cityblock', 'l1', 'seuclidean'} or a callable. Got 'str' instead.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'p', 'mahalanobis', 'precomputed', 'canberra', 'jaccard', 'seuclidean', 'yule', 'correlation', 'chebyshev', 'pyfunc', 'russellrao', 'rogerstanimoto', 'braycurtis', 'l2', 'dice', 'cosine', 'hamming', 'haversine', 'sqeuclidean', 'infinity', 'sokalmichener', 'l1', 'manhattan', 'cityblock', 'euclidean', 'minkowski', 'nan_euclidean', 'sokalsneath'} or a callable. Got 'str' instead.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'sokalmichener', 'chebyshev', 'russellrao', 'sqeuclidean', 'haversine', 'pyfunc', 'infinity', 'mahalanobis', 'l1', 'minkowski', 'jaccard', 'precomputed', 'canberra', 'dice', 'manhattan', 'cityblock', 'euclidean', 'rogerstanimoto', 'yule', 'hamming', 'sokalsneath', 'cosine', 'braycurtis', 'nan_euclidean', 'p', 'l2', 'correlation', 'seuclidean'} or a callable. Got 'str' instead.

--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'russellrao', 'euclidean', 'p', 'minkowski', 'yule', 'rogerstanimoto', 'pyfunc', 'sqeuclidean', 'nan_euclidean', 'dice', 'jaccard', 'cosine', 'canberra', 'braycurtis', 'sokalsneath', 'cityblock', 'infinity', 'l1', 'sokalmichener', 'haversine', 'seuclidean', 'hamming', 'l2', 'manhattan', 'precomputed', 'chebyshev', 'mahalanobis', 'correlation'} or a callable. Got 'str' instead.

--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'dice', 'sqeuclidean', 'minkowski', 'pyfunc', 'haversine', 'nan_euclidean', 'l1', 'l2', 'yule', 'cityblock', 'sokalsneath', 'correlation', 'euclidean', 'precomputed', 'braycurtis', 'rogerstanimoto', 'p', 'canberra', 'seuclidean', 'jaccard', 'mahalanobis', 'hamming', 'cosine', 'infinity', 'chebyshev', 'sokalmichener', 'russellrao', 'manhattan'} or a callable. Got 'str' instead.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'dice', 'rogerstanimoto', 'jaccard', 'euclidean', 'hamming', 'cosine', 'chebyshev', 'p', 'haversine', 'mahalanobis', 'canberra', 'minkowski', 'braycurtis', 'sokalmichener', 'nan_euclidean', 'l2', 'infinity', 'l1', 'seuclidean', 'pyfunc', 'manhattan', 'russellrao', 'precomputed', 'correlation', 'yule', 'sqeuclidean', 'cityblock', 'sokalsneath'} or a callable. Got 'str' instead.

--------------------------------------------------------------------------------
18 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'metric' parameter of KNeighborsClassifier must be a str among {'mahalanobis', 'cityblock', 'nan_euclidean', 'precomputed', 'euclidean', 'braycurtis', 'cosine', 'yule', 'sokalsneath', 'infinity', 'seuclidean', 'rogerstanimoto', 'canberra', 'l2', 'dice', 'sqeuclidean', 'sokalmichener', 'jaccard', 'p', 'hamming', 'chebyshev', 'l1', 'manhattan', 'russellrao', 'haversine', 'pyfunc', 'minkowski', 'correlation'} or a callable. Got 'str' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [0.9590177  0.96273717 0.92974074 0.95904674 0.94447046 0.94447046
        nan        nan        nan        nan        nan        nan
 0.9590177  0.96273717 0.92974074 0.95904674 0.94447046 0.94447046
        nan        nan        nan        nan        nan        nan
 0.9590177  0.96273717 0.92974074 0.95904674 0.94447046 0.94447046
        nan        nan        nan        nan        nan        nan
 0.9590177  0.96273717 0.92974074 0.95904674 0.94447046 0.94447046
        nan        nan        nan        nan        nan        nan]
  warnings.warn(
C:\Users\Karpagavalli\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski', 'str'],
                         'n_neighbors': [5, 6, 7],
                         'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [15]:
re=grid.cv_results_
y_pred=grid.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

print("The confusion matrix is:\n\n",cm,"\n\n")
print("The classification report is :\n\n",clf_report)

The confusion matrix is:

 [[51  0]
 [ 8 74]]


The classification report is :

               precision    recall  f1-score   support

           0       0.86      1.00      0.93        51
           1       1.00      0.90      0.95        82

    accuracy                           0.94       133
   macro avg       0.93      0.95      0.94       133
weighted avg       0.95      0.94      0.94       133

In [17]:
from sklearn.metrics import f1_score
f1_scr=f1_score(y_test,y_pred,average='weighted')
print("The f1_score for bestparameter is {}:".format(grid.best_params_),f1_scr)

The f1_score for bestparameter is {'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 5, 'weights': 'distance'}: 0.9404945931261721

In [18]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [19]:
table=pd.DataFrame.from_dict(re)

In [20]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005559,0.004590,0.257552,0.005151,auto,minkowski,5,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.963284,0.962636,0.944023,0.962573,0.962573,0.959018,0.007502,9
1,0.004794,0.005810,0.233635,0.019122,auto,minkowski,5,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.963284,0.981233,0.944023,0.962573,0.962573,0.962737,0.011770,1
2,0.002997,0.003962,0.131046,0.092191,auto,minkowski,6,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.890759,0.925764,0.907035,0.962573,0.962573,0.929741,0.029006,21
3,0.012016,0.006008,0.053162,0.007642,auto,minkowski,6,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.963284,0.962636,0.925524,0.981217,0.962573,0.959047,0.018213,5
4,0.006239,0.007642,0.053242,0.007646,auto,minkowski,7,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,13
5,0.005211,0.005696,0.053248,0.005095,auto,minkowski,7,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,13
6,0.000000,0.000000,0.000000,0.000000,auto,str,5,uniform,"{'algorithm': 'auto', 'metric': 'str', 'n_neig...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
7,0.000000,0.000000,0.000000,0.000000,auto,str,5,distance,"{'algorithm': 'auto', 'metric': 'str', 'n_neig...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
8,0.003125,0.006250,0.000000,0.000000,auto,str,6,uniform,"{'algorithm': 'auto', 'metric': 'str', 'n_neig...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
9,0.000000,0.000000,0.000000,0.000000,auto,str,6,distance,"{'algorithm': 'auto', 'metric': 'str', 'n_neig...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
10,0.000000,0.000000,0.000000,0.000000,auto,str,7,uniform,"{'algorithm': 'auto', 'metric': 'str', 'n_neig...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
11,0.000000,0.000000,0.000000,0.000000,auto,str,7,distance,"{'algorithm': 'auto', 'metric': 'str', 'n_neig...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
12,0.027330,0.006104,0.021715,0.004758,ball_tree,minkowski,5,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.963284,0.962636,0.944023,0.962573,0.962573,0.959018,0.007502,9
13,0.007061,0.005494,0.010737,0.008813,ball_tree,minkowski,5,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.963284,0.981233,0.944023,0.962573,0.962573,0.962737,0.011770,1
14,0.010564,0.009250,0.012651,0.007158,ball_tree,minkowski,6,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.890759,0.925764,0.907035,0.962573,0.962573,0.929741,0.029006,21
15,0.027688,0.022684,0.011137,0.006109,ball_tree,minkowski,6,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.963284,0.962636,0.925524,0.981217,0.962573,0.959047,0.018213,5
16,0.013635,0.004810,0.012296,0.005272,ball_tree,minkowski,7,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,13
17,0.011951,0.012252,0.003445,0.003365,ball_tree,minkowski,7,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,13
18,0.000000,0.000000,0.000000,0.000000,ball_tree,str,5,uniform,"{'algorithm': 'ball_tree', 'metric': 'str', 'n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
19,0.000202,0.000403,0.000000,0.000000,ball_tree,str,5,distance,"{'algorithm': 'ball_tree', 'metric': 'str', 'n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
20,0.000000,0.000000,0.000000,0.000000,ball_tree,str,6,uniform,"{'algorithm': 'ball_tree', 'metric': 'str', 'n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
21,0.003138,0.006277,0.000000,0.000000,ball_tree,str,6,distance,"{'algorithm': 'ball_tree', 'metric': 'str', 'n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
22,0.000000,0.000000,0.000000,0.000000,ball_tree,str,7,uniform,"{'algorithm': 'ball_tree', 'metric': 'str', 'n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
23,0.003847,0.007694,0.000000,0.000000,ball_tree,str,7,distance,"{'algorithm': 'ball_tree', 'metric': 'str', 'n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
24,0.026043,0.021988,0.012960,0.005144,kd_tree,minkowski,5,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.963284,0.962636,0.944023,0.962573,0.962573,0.959018,0.007502,9
25,0.019284,0.012321,0.012289,0.006230,kd_tree,minkowski,5,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.963284,0.981233,0.944023,0.962573,0.962573,0.962737,0.011770,1
26,0.012976,0.011413,0.009765,0.006808,kd_tree,minkowski,6,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.890759,0.925764,0.907035,0.962573,0.962573,0.929741,0.029006,21
27,0.024040,0.013653,0.010057,0.006032,kd_tree,minkowski,6,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.963284,0.962636,0.925524,0.981217,0.962573,0.959047,0.018213,5
28,0.008162,0.006763,0.011892,0.006079,kd_tree,minkowski,7,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,13
29,0.007848,0.006046,0.003128,0.006256,kd_tree,minkowski,7,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,13
30,0.000469,0.000584,0.000000,0.000000,kd_tree,str,5,uniform,"{'algorithm': 'kd_tree', 'metric': 'str', 'n_n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
31,0.000209,0.000418,0.000000,0.000000,kd_tree,str,5,distance,"{'algorithm': 'kd_tree', 'metric': 'str', 'n_n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
32,0.000000,0.000000,0.000000,0.000000,kd_tree,str,6,uniform,"{'algorithm': 'kd_tree', 'metric': 'str', 'n_n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
33,0.000000,0.000000,0.000000,0.000000,kd_tree,str,6,distance,"{'algorithm': 'kd_tree', 'metric': 'str', 'n_n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
34,0.002902,0.005804,0.000000,0.000000,kd_tree,str,7,uniform,"{'algorithm': 'kd_tree', 'metric': 'str', 'n_n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
35,0.002902,0.005804,0.000000,0.000000,kd_tree,str,7,distance,"{'algorithm': 'kd_tree', 'metric': 'str', 'n_n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
36,0.003126,0.006253,0.043153,0.004570,brute,minkowski,5,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.963284,0.962636,0.944023,0.962573,0.962573,0.959018,0.007502,9
37,0.008558,0.011867,0.044402,0.012061,brute,minkowski,5,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.963284,0.981233,0.944023,0.962573,0.962573,0.962737,0.011770,1
38,0.012503,0.011693,0.041858,0.006434,brute,minkowski,6,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.890759,0.925764,0.907035,0.962573,0.962573,0.929741,0.029006,21
39,0.000000,0.000000,0.039426,0.009346,brute,minkowski,6,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.963284,0.962636,0.925524,0.981217,0.962573,0.959047,0.018213,5
40,0.014346,0.017805,0.041940,0.009683,brute,minkowski,7,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,13
41,0.009374,0.007654,0.034401,0.006241,brute,minkowski,7,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,13
42,0.000000,0.000000,0.000000,0.000000,brute,str,5,uniform,"{'algorithm': 'brute', 'metric': 'str', 'n_nei...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
43,0.000000,0.000000,0.000000,0.000000,brute,str,5,distance,"{'algorithm': 'brute', 'metric': 'str', 'n_nei...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
44,0.000000,0.000000,0.000000,0.000000,brute,str,6,uniform,"{'algorithm': 'brute', 'metric': 'str', 'n_nei...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
45,0.003126,0.006253,0.000000,0.000000,brute,str,6,distance,"{'algorithm': 'brute', 'metric': 'str', 'n_nei...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
46,0.000000,0.000000,0.000000,0.000000,brute,str,7,uniform,"{'algorithm': 'brute', 'metric': 'str', 'n_nei...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
47,0.003123,0.006247,0.000000,0.000000,brute,str,7,distance,"{'algorithm': 'brute', 'metric': 'str', 'n_nei...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25

In [ ]:
age=float(input("Age:"))
bp=float(input("BP:"))
al=int(input("Al:"))
su=int(input("Sugar:"))
bgr=float(input("bgr:"))
bu=float(input("bu:"))
sc=float(input("sc:"))
Sod=float(input("sod:"))
pot=float(input("pot:"))
hrmo=float(input("hrmo:"))
pcv=float(input("pcv:"))
wc=float(input("wc:"))
rc=float(input("rc:"))
sg_b=int(input("sg_b_0_or_1:"))
sg_c=int(input("sg_c_0_or_1:"))
sg_d=int(input("sg_d_0_or_1:"))
sg_e=int(input("sg_e_0_or_1:"))
rbc_normal=int(input("rbc_normal_0_or_1:"))
pc_normal=int(input("pc_normal_0_or_1:"))
pcc_present=int(input("pcc_present_0_or_1:"))
ba_present=int(input("ba_present_0_or_1:"))
htn_yes=int(input("htn_yes_0_or_1:"))
dm_yes=int(input("dm_yes_0_or_1:"))
cad_yes=int(input("cad_yes_0_or_1:"))
appet_yes=int(input("appet_yes_0_or_1:"))
pe_yes=int(input("pe_yes_0_or_1:"))
ane_yes=int(input("ane_yes_0_or_1:"))

In [26]:
Future_Prediction=grid.predict([[age, bp, al, su, bgr, bu, sc, Sod, pot, hrmo, pcv,wc, rc, sg_b, sg_c, sg_d,sg_e, rbc_normal,pc_normal,pcc_present, ba_present, htn_yes, dm_yes, cad_yes,appet_yes, pe_yes, ane_yes]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]